OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:39:55
// Original T-count: 14
// Total gates: 36

qreg q[2];

cx q[0],q[1];
t q[1];
cx q[0],q[1];
cx q[1],q[0];
t q[0];
cx q[1],q[0];
s q[0];
s q[1];
cx q[0],q[1];
sdg q[1];
cx q[0],q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
t q[0];
t q[0];
t q[1];
t q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
cx q[1],q[0];
t q[0];
cx q[1],q[0];
s q[0];
s q[1];
cx q[0],q[1];
sdg q[1];
cx q[0],q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
t q[0];
t q[0];
t q[1];
t q[1];

// Gate statistics:
// CNOT: 16
// T-gates: 14 (T: 14, T†: 0)
// S-gates: 6
// Z-gates: 0