OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:39:55
// Original T-count: 0
// Total gates: 2

qreg q[2];

z q[0];
z q[1];

// Gate statistics:
// CNOT: 0
// T-gates: 0 (T: 0, T†: 0)
// S-gates: 0
// Z-gates: 2