OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:39:55
// Original T-count: 0
// Total gates: 3

qreg q[2];

cx q[1],q[0];
s q[0];
cx q[1],q[0];

// Gate statistics:
// CNOT: 2
// T-gates: 0 (T: 0, T†: 0)
// S-gates: 1
// Z-gates: 0