OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:39:55
// Original T-count: 3
// Total gates: 5

qreg q[2];

t q[0];
z q[0];
t q[1];
z q[1];
cx q[1],q[0];
t q[0];
cx q[1],q[0];

// Gate statistics:
// CNOT: 2
// T-gates: 3 (T: 3, T†: 0)
// S-gates: 0
// Z-gates: 2