OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:39:55
// Original T-count: 15
// Total gates: 35

qreg q[2];

t q[0];
t q[0];
t q[1];
t q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
cx q[1],q[0];
t q[0];
cx q[1],q[0];
s q[0];
s q[1];
cx q[0],q[1];
sdg q[1];
cx q[0],q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
cx q[1],q[0];
t q[0];
cx q[1],q[0];
s q[0];
s q[1];
cx q[0],q[1];
sdg q[1];
cx q[0],q[1];
t q[1];
t q[1];
t q[0];
t q[0];
tdg q[0];
tdg q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];

// Gate statistics:
// CNOT: 14
// T-gates: 15 (T: 13, T†: 2)
// S-gates: 6
// Z-gates: 0