OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:39:55
// Original T-count: 3
// Total gates: 5

qreg q[2];

tdg q[0];
tdg q[1];
cx q[1],q[0];
t q[0];
cx q[1],q[0];

// Gate statistics:
// CNOT: 2
// T-gates: 3 (T: 1, T†: 2)
// S-gates: 0
// Z-gates: 0