OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 02:25:02
// Original T-count: 3
// Total gates: 7

qreg q[3];

tdg q[0];
t q[1];
s q[1];
cx q[1],q[0];
cx q[2],q[0];
t q[0];
s q[0];
cx q[2],q[0];
cx q[1],q[0];

// Gate statistics:
// CNOT: 4
// T-gates: 3 (T: 2, T†: 1)
// S-gates: 2 (S: 2, S†: 0)
// Z-gates: 0