OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 02:25:02
// Original T-count: 1
// Total gates: 7

qreg q[4];

tdg q[0];
z q[1];
cx q[1],q[0];
cx q[2],q[0];
sdg q[0];
cx q[2],q[0];
cx q[1],q[0];

// Gate statistics:
// CNOT: 4
// T-gates: 1 (T: 0, T†: 1)
// S-gates: 1 (S: 0, S†: 1)
// Z-gates: 1