OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 02:25:02
// Original T-count: 3
// Total gates: 13

qreg q[3];

cx q[0],q[2];
cx q[1],q[2];
t q[2];
cx q[1],q[2];
cx q[0],q[2];
s q[1];
cx q[0],q[2];
cx q[1],q[2];
s q[2];
cx q[1],q[2];
cx q[0],q[2];
t q[1];
tdg q[0];

// Gate statistics:
// CNOT: 8
// T-gates: 3 (T: 2, T†: 1)
// S-gates: 2 (S: 2, S†: 0)
// Z-gates: 0