OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 02:25:02
// Original T-count: 5
// Total gates: 24

qreg q[4];

cx q[0],q[2];
cx q[1],q[2];
t q[2];
cx q[1],q[2];
cx q[0],q[2];
s q[1];
cx q[0],q[2];
cx q[1],q[2];
s q[2];
cx q[1],q[2];
cx q[0],q[2];
tdg q[0];
t q[1];
cx q[0],q[2];
cx q[1],q[2];
t q[2];
cx q[1],q[2];
cx q[0],q[2];
t q[1];
cx q[0],q[2];
cx q[1],q[2];
s q[2];
cx q[1],q[2];
cx q[0],q[2];

// Gate statistics:
// CNOT: 16
// T-gates: 5 (T: 4, T†: 1)
// S-gates: 3 (S: 3, S†: 0)
// Z-gates: 0