OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:10:05
// Original T-count: 1
// Total gates: 4

qreg q[2];

tdg q[0];
cx q[1],q[0];
z q[0];
cx q[1],q[0];

// Gate statistics:
// CNOT: 2
// T-gates: 1 (T: 0, T†: 1)
// S-gates: 0 (S: 0, S†: 0)
// Z-gates: 1