OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:10:05
// Original T-count: 2
// Total gates: 2

qreg q[2];

t q[0];
s q[0];
t q[1];
s q[1];

// Gate statistics:
// CNOT: 0
// T-gates: 2 (T: 2, T†: 0)
// S-gates: 2 (S: 2, S†: 0)
// Z-gates: 0