OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:10:05
// Original T-count: 12
// Total gates: 35

qreg q[2];

t q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
s q[1];
cx q[0],q[1];
sdg q[1];
cx q[0],q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
tdg q[0];
t q[0];
cx q[0],q[1];
s q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
s q[1];
cx q[0],q[1];
sdg q[1];
cx q[0],q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
tdg q[0];
t q[0];
cx q[0],q[1];
s q[1];
cx q[0],q[1];
t q[1];
tdg q[0];
s q[1];

// Gate statistics:
// CNOT: 16
// T-gates: 12 (T: 9, T†: 3)
// S-gates: 7 (S: 5, S†: 2)
// Z-gates: 0