OPENQASM 2.0;
include "qelib1.inc";

// Generated by rmsynth on 2026-02-01 03:10:05
// Original T-count: 5
// Total gates: 14

qreg q[2];

cx q[0],q[1];
t q[1];
cx q[0],q[1];
tdg q[1];
s q[1];
cx q[0],q[1];
t q[1];
cx q[0],q[1];
tdg q[0];
t q[1];
cx q[0],q[1];
s q[1];
cx q[0],q[1];
sdg q[1];

// Gate statistics:
// CNOT: 6
// T-gates: 5 (T: 3, T†: 2)
// S-gates: 3 (S: 2, S†: 1)
// Z-gates: 0